tests, pkg/lightning: migrate lightning test view
Signed-off-by: Neil Shen <overvenus@gmail.com>

diff --git a/tests/_utils/check_not_contains b/tests/_utils/check_not_contains
--- a/tests/_utils/check_not_contains
+++ b/tests/_utils/check_not_contains
@@ -15,15 +15,10 @@
 
 set -eu
 
-TEST_DIR=/tmp/backup_restore_test
-
-SQL="$1"
-shift
-
-echo "[$(date)] Executing SQL: $SQL" > "$TEST_DIR/sql_res.$TEST_NAME.txt"
-mysql -uroot -h127.0.0.1 -P4000 \
-    --ssl-ca="$TEST_DIR/tls/ca.pem" \
-    --ssl-cert="$TEST_DIR/tls/curl.pem" \
-    --ssl-key="$TEST_DIR/tls/curl.key" \
-    "$@" \
-    --default-character-set utf8 -E -e "$SQL" >> "$TEST_DIR/sql_res.$TEST_NAME.txt"
+if grep -Fq "$1" "$TEST_DIR/sql_res.$TEST_NAME.txt"; then
+    echo "TEST FAILED: OUTPUT CONTAINS '$1'"
+    echo "____________________________________"
+    cat "$TEST_DIR/sql_res.$TEST_NAME.txt"
+    echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
+    exit 1
+fi
