tests: inline try to start tiflash

diff --git a/tests/_utils/run_services b/tests/_utils/run_services
--- a/tests/_utils/run_services
+++ b/tests/_utils/run_services
@@ -15,7 +15,7 @@
 
 set -eu
 
-TEST_DIR=./tmp/backup_restore_test
+TEST_DIR=/tmp/backup_restore_test
 
 PD_ADDR="127.0.0.1:2379"
 TIDB_IP="127.0.0.1"
@@ -34,18 +34,6 @@ stop_services() {
     killall -9 tiflash || true
 
     find "$TEST_DIR" -maxdepth 1 -not -path "$TEST_DIR" -not -name "*.log" | xargs rm -r || true
-}
-
-try() {
-    echo "trying ${@:2}"
-    for i in `seq $1`; do
-        if ${@:2}; then
-            return
-        fi
-        sleep 3
-    done
-    echo "failed to execute ${@:2} after retry $1 times"
-    exit 10
 }
 
 start_services() {
@@ -129,7 +117,15 @@ start_services() {
     echo "Starting TiFlash..."
     LD_LIBRARY_PATH=bin/ bin/tiflash server --config-file=$TIFLASH_CONFIG &
 
-    try 3 "bin/pd-ctl store | grep tiflash"
+    i=0
+    while ! bin/pd-ctl store | grep tiflash; do
+        i=$((i+1))
+        if [ $i -gt 5 ]; then
+            echo "failed to start tiflash"
+            exit 1
+        fi
+        sleep 3
+    done
 }
 
 start_services_withTLS() {
