*: add more debug logs
Why start tiflash seems... blockes... ????

diff --git a/tests/_utils/run_services b/tests/_utils/run_services
--- a/tests/_utils/run_services
+++ b/tests/_utils/run_services
@@ -104,18 +104,10 @@ start_services() {
         sleep 3
     done
 
-    i=0
-    while ! curl "http://$PD_ADDR/pd/api/v1/cluster/status" -sf | grep -q "\"is_initialized\": true"; do
-        i=$((i+1))
-        if [ "$i" -gt 20 ]; then
-            echo 'Failed to bootstrap cluster'
-            exit 1
-        fi
-        sleep 3
-    done
-    
+        
     echo "Starting TiFlash..."
     LD_LIBRARY_PATH=bin/ bin/tiflash server --config-file=$TIFLASH_CONFIG &
+    echo "TiFlash started..."
 
     i=0
     while ! bin/pd-ctl store | grep "tiflash"; do
@@ -125,6 +117,16 @@ start_services() {
             exit 1
         fi
         echo "TiFlash seems doesn't started, retrying..."
+        sleep 3
+    done
+
+    i=0
+    while ! curl "http://$PD_ADDR/pd/api/v1/cluster/status" -sf | grep -q "\"is_initialized\": true"; do
+        i=$((i+1))
+        if [ "$i" -gt 20 ]; then
+            echo 'Failed to bootstrap cluster'
+            exit 1
+        fi
         sleep 3
     done
 }
