cherry pick #1019 to release-4.0
Signed-off-by: ti-srebot <ti-srebot@pingcap.com>

diff --git a/tests/_utils/run_services b/tests/_utils/run_services
--- a/tests/_utils/run_services
+++ b/tests/_utils/run_services
@@ -28,6 +28,7 @@ export TIKV_COUNT=3
 export TIFLASH_STATUS="127.0.0.1:17000"
 export TIFLASH_HTTP="127.0.0.1:8125"
 export IMPORTER_ADDR="127.0.0.1:8808"
+export TIKV_PIDS="${TEST_DIR:?}/tikv_pids.txt"
 
 cleanup_data() {
     # Clean up data
@@ -36,18 +37,29 @@ cleanup_data() {
     done
 }
 
+stop() {
+    svc=$1
+    killall -v -1 "$svc" 2>/dev/null || return 0
+    sleep 1 # give some grace shutdown period
+    killall -v -9 "$svc" &>/dev/null || return 0
+}
+
 stop_services() {
     for svc in "br" "tidb-server" "tiflash" "TiFlashMain" "tikv-server" "pd-server" "cdc" "minio" "tikv-importer"; do
-        killall -v -1 $svc 2>/dev/null || continue
-        sleep 1 # give some grace shutdown period
-        killall -v -9 $svc &>/dev/null || continue
+        stop $svc &
     done
+<<<<<<< HEAD
+=======
+    sleep 2 # give some time for the OS to reap all processes
+    lsof -n -P -i :2379 -i :4000 -i :10080 -i :20161 -i :20162 -i :20163 -i :20181 -i :20182 -i :20183 -i :17000 -i :8125 || true
+>>>>>>> 264059b7... backup: allow backup tolerate minor TiKV failure (#997) (#1019)
 }
 
 start_services() {
     max_retry=3
     for retry_time in $(seq 1 $max_retry); do
-        if start_services_impl $@; then
+        # run it in a subshell so the failure won't stop execution.
+        if ( start_services_impl "$@" ); then
             return 0
         fi
         stop_services
@@ -58,36 +70,7 @@ start_services() {
     return 1
 }
 
-start_services_impl() {
-    stop_services || true
-    cleanup_data || true
-
-    TIDB_CONFIG="tests/config/tidb.toml"
-    TIKV_CONFIG="tests/config/tikv.toml"
-    PD_CONFIG="tests/config/pd.toml"
-    RUN_TIFLASH="YES"
-
-    while [[ $# -gt 0 ]]
-    do
-        local key="$1"
-
-        case $key in
-            --tidb-cfg)
-            TIDB_CONFIG="$2"
-            shift # past argument
-            shift # past value
-            ;;
-            --no-tiflash)
-            RUN_TIFLASH="NO"
-            shift # past argument
-            ;;
-            *)    # unknown option
-            echo "Unknown args $@"
-            exit 1
-            ;;
-        esac
-    done
-
+start_pd() {
     echo "Starting PD..."
     mkdir -p "$TEST_DIR/pd"
     bin/pd-server \
@@ -106,20 +89,62 @@ start_services_impl() {
        fi
        sleep 3
     done
+}
 
-    echo "Starting TiKV..."
-    for i in $(seq $TIKV_COUNT); do
-        mkdir -p "$TEST_DIR/tikv${i}"
-        bin/tikv-server \
-            --pd "$PD_ADDR" \
-            -A "$TIKV_ADDR$i" \
-            --status-addr "$TIKV_STATUS_ADDR$i" \
-            --log-file "$TEST_DIR/tikv${i}.log" \
-            --log-level info \
-            -C "$TIKV_CONFIG" \
-            -s "$TEST_DIR/tikv${i}" &
+kv_outage() {
+    dur=""
+    id=()
+    scale_in=false
+    scale_out=false
+    until [ $# -eq 0 ]; do
+        case $1 in
+            --duration | -d) shift; dur=$1 ;;
+            --id | -i) shift; id+=("$1") ;;
+            --scale-out) scale_out=true ;;
+            --kill) scale_in=true ;;
+        esac
+        shift
     done
 
+    $scale_out || { 
+        for i in "${id[@]}"; do
+            target=$(cat "${TIKV_PIDS}_$i" | awk '{print $1}')
+            echo "killing TiKV $target(#$i)"
+            kill "$target" || true
+            sleep 1
+            kill -9 "$target" || true
+        done 
+    }
+    $scale_in || $scale_out || sleep "$dur"
+    $scale_in || {
+        for i in "${id[@]}"; do
+            if [ -e "${TIKV_PIDS}_$i" ]; then
+                TIKV_CONFIG=$(cat "${TIKV_PIDS}_$i" | awk '{print $2}')
+            else
+                TIKV_CONFIG=${TIKV_CONFIG:-"tests/config/tikv.toml"}
+            fi
+            start_tikv "$i"
+        done
+    }
+}
+
+start_tikv() {
+    i=$1
+    echo "Starting TiKV($i)..."
+    mkdir -p "$TEST_DIR/tikv${i}"
+    bin/tikv-server \
+        --pd "$PD_ADDR" \
+        -A "$TIKV_ADDR$i" \
+        --status-addr "$TIKV_STATUS_ADDR$i" \
+        --log-file "$TEST_DIR/tikv${i}.log" \
+        --log-level info \
+        -C "$TIKV_CONFIG" \
+        -s "$TEST_DIR/tikv${i}" &
+    pid=$!
+    echo -e "$pid\t$TIKV_CONFIG" > "${TIKV_PIDS}_${i}"
+}
+
+ensure_tikv() {
     echo "Waiting initializing TiKV..."
     while ! run_curl "https://$PD_ADDR/pd/api/v1/cluster/status" | grep '"is_initialized": true'; do
        i=$((i+1))
@@ -129,7 +154,9 @@ start_services_impl() {
        fi
        sleep 5
     done
+}
 
+start_tidb() {
     echo "Starting TiDB..."
     bin/tidb-server \
         -P 4000 \
@@ -150,18 +177,60 @@ start_services_impl() {
         fi
         sleep 3
     done
+}
 
+start_importer() {
     echo "Starting Importer..."
     bin/tikv-importer \
         --addr "$IMPORTER_ADDR" \
         --import-dir "$TEST_DIR/importer" \
         --log-file "$TEST_DIR/importer.log" \
         --config "tests/config/importer.toml" &
+}
 
-    if [[ $RUN_TIFLASH == "YES" ]]; then
-        if ! start_tiflash; then
-            return 1
-        fi
+
+start_services_impl() {
+    stop_services || true
+    cleanup_data || true
+
+    TIDB_CONFIG="tests/config/tidb.toml"
+    TIKV_CONFIG="tests/config/tikv.toml"
+    PD_CONFIG="tests/config/pd.toml"
+    RUN_TIFLASH=true
+
+    while [[ $# -gt 0 ]]
+    do
+        local key="$1"
+
+        case $key in
+            --tidb-cfg)
+            TIDB_CONFIG="$2"
+            shift # past argument
+            shift # past value
+            ;;
+            --no-tiflash)
+            RUN_TIFLASH=false
+            shift # past argument
+            ;;
+            *)    # unknown option
+            echo "Unknown args $1"
+            exit 1
+            ;;
+        esac
+    done
+
+    rm -f "${TIKV_PIDS}*"
+
+    start_pd
+    for i in $(seq $TIKV_COUNT); do
+        start_tikv "$i"
+    done
+    ensure_tikv
+    start_tidb
+    start_importer
+
+    if $RUN_TIFLASH; then
+        start_tiflash
     fi
 
     i=0
