tests: stable cluster start up
Signed-off-by: Neil Shen <overvenus@gmail.com>

diff --git a/tests/_utils/run_services b/tests/_utils/run_services
--- a/tests/_utils/run_services
+++ b/tests/_utils/run_services
@@ -39,6 +39,7 @@ start_services() {
     stop_services
 
     echo "Starting PD..."
+    mkdir -p "$TEST_DIR/pd"
     bin/pd-server \
         --client-urls "http://$PD_ADDR" \
         --log-file "$TEST_DIR/pd.log" \
@@ -56,6 +57,7 @@ start_services() {
 
     echo "Starting TiKV..."
     for i in $(seq $TIKV_COUNT); do
+        mkdir -p "$TEST_DIR/tikv${i}"
         bin/tikv-server \
             --pd "$PD_ADDR" \
             -A "$TIKV_ADDR$i" \
@@ -64,7 +66,16 @@ start_services() {
             -C "tests/config/tikv.toml" \
             -s "$TEST_DIR/tikv${i}" &
     done
-    sleep 1
+
+    echo "Waiting initializing TiKV..."
+    while ! curl -sf "http://$PD_ADDR/pd/api/v1/cluster/status" | grep '"is_initialized": true'; do
+       i=$((i+1))
+       if [ "$i" -gt 10 ]; then
+          echo 'Failed to initialize TiKV cluster'
+          exit 1
+       fi
+       sleep 3
+    done
 
     echo "Starting TiDB..."
     bin/tidb-server \
@@ -136,7 +147,18 @@ start_services_withTLS() {
             -C "$TIKV_CONFIG" \
             -s "$TEST_DIR/tikv${i}" &
     done
-    sleep 1
+
+    echo "Waiting initializing TiKV..."
+    while ! curl -k --cert $1/certificates/client.pem \
+            --key $1/certificates/client-key.pem \
+            -sf "https://$PD_ADDR/pd/api/v1/cluster/status" | grep '"is_initialized": true'; do
+       i=$((i+1))
+       if [ "$i" -gt 10 ]; then
+          echo 'Failed to initialize TiKV cluster'
+          exit 1
+       fi
+       sleep 3
+    done
 
     echo "Starting TiDB..."
     bin/tidb-server \
