*: add test case of tiflash

diff --git a/tests/_utils/run_services b/tests/_utils/run_services
--- a/tests/_utils/run_services
+++ b/tests/_utils/run_services
@@ -31,8 +31,21 @@ stop_services() {
     killall -9 tikv-server || true
     killall -9 pd-server || true
     killall -9 tidb-server || true
+    killall -9 tiflash || true
 
     find "$TEST_DIR" -maxdepth 1 -not -path "$TEST_DIR" -not -name "*.log" | xargs rm -r || true
+}
+
+try() {
+    echo "trying ${@:2}"
+    for i in `seq $1`; do
+        if ${@:2}; then
+            return
+        fi
+        sleep 3
+    done
+    echo "failed to execute ${@:2} after retry $1 times"
+    exit 10
 }
 
 start_services() {
@@ -100,6 +113,9 @@ start_services() {
         sleep 3
     done
 
+    echo "Enabling placement rules..."
+    bin/pd-ctl config placement-rules enable
+
     i=0
     while ! curl "http://$PD_ADDR/pd/api/v1/cluster/status" -sf | grep -q "\"is_initialized\": true"; do
         i=$((i+1))
@@ -109,6 +125,11 @@ start_services() {
         fi
         sleep 3
     done
+    
+    echo "Starting TiFlash..."
+    LD_LIBRARY_PATH=bin/ bin/tiflash server --config-file=tests/config/tiflash.toml &
+
+    try 3 "bin/pd-ctl store | grep tiflash"
 }
 
 start_services_withTLS() {
